Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace MainProgram.Models
{
	public class Department
	{
        public int id { get; set; }
        [Required]
        [MaxLength(5)]
        public string name { get; set; }
        public string manager { get; set; }
        public virtual List<course>?Courses { get; set; }
        public virtual List<instructor>? Instructors { get; set;}
		public virtual List<trainee>? Trainees { get; set;}

    }
}

Controllers/departmentController.cs
using MainProgram.Models;
using Microsoft.AspNetCore.Mvc;

namespace MainProgram.Controllers
{
	public class departmentController : Controller
	{
		itientities context = new itientities();
		public IActionResult Index()
		{
			List<Department> departmentList = context.departments.ToList();
			return View(departmentList);
		}
		public IActionResult showcousesindepartment(int deptid)
		{
              List<course>courses=context.Courses.Where(c=>c.dep_id==deptid).ToList();
			return Json(courses);


		}
		public IActionResult departmentbyid(int id)
		{
			Department dept = context.departments.FirstOrDefault(d => d.id == id);

			return View(dept);

		}
		
		public IActionResult newdept(Department de)
		{
			

           return View(de);
		}
		public IActionResult savenewdept(Department dept)
		{
			if (dept.name != null)
			{


				context.departments.Add(dept);
				context.SaveChanges();
				return RedirectToAction("Index");
			}
			return RedirectToAction("newdept", dept);
    	}
		public IActionResult edit(int id)
		{
		 Department dept=context.departments.FirstOrDefault(d => d.id == id);

			return View(dept);
		}
		public IActionResult saveedit(int id, Department dept)
		{
			var deptartment=context.departments.FirstOrDefault(de => de.id == id);
		
			
				 deptartment.name= dept.name;
				deptartment.manager= dept.manager;
			context.SaveChanges();

				return RedirectToAction("Index");
			
		
		}

    }
}

Views/department/Index.cshtml
@model List<Department>
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
    SelectList listt = new SelectList(Model, "id", "name");

}



<table class="table table-borderd hover">
    <tr>
        <th>id</th>
        <th>name</th>
        <th>manager</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.id</td>
            <td>@item.name</td>
            <td>@item.manager</td>
            <td><a href="/department/edit/@item.id">Edit</a></td>
        </tr>
    }

</table>
<a asp-action="newdept" asp-controller="department">Add New Deparment</a>

<br />
<br />
<label>Selecte department to show all courses</label>
<select class="form-control" name="dept" id="dept" asp-items="listt" onchange="getcourses()"></select>

<select class="form-control" name="course" id="cid"></select>



<script src="/lib/jquery/dist/jquery.min.js"></script>

<script>
    function getcourses() {
        console.log(document.getElementById("dept"));
        var id = document.getElementById("dept").value;

        $.ajax({
            url: "/department/showcousesindepartment?deptid=" + id, success: function (result) {

                document.getElementById("cid").innerHTML = "";
                console.log(result)
                for (let course of result) {

                    document.getElementById("cid").innerHTML += "<option value='" + course.id + "'>"course.name"</option>";
                }

            }
        });

    }


</script>

Views/department/departmentbyid.cshtml
@model Department
@{
    ViewData["Title"] = "departmentbyid";
}

<div class="div1">
    <h3>@Model.id</h3>
    <h3>@Model.name</h3>
    <h3>@Model.manager</h3>

</div>
<h1>departmentbyid</h1>

<style>

.div1{

  position:absolut;
  top:50%;
  left:50%
   transform-translate:-50% -50%
}

</style>

Views/department/edit.cshtml
@model Department
@{
    ViewData["Title"] = "edit";
}

<h1>edit</h1>
<br />
<form action="/department/saveedit/@Model.id" method="post">
    
   @*  <div>
        <label>name</label>
            <input type="text" class="form-control" name="@Model.name" value="@Model.name" />
    </div> *@
    <lable> dept name</lable>
    @Html.TextBox("name",Model.name,new{@class="form-control",style="width=100px;hight=30px"})
   @*  <div>
        <label>manager</label>
       <input type="text" class="form-control" name="@Model.manager" value="@Model.manager" />
    </div> *@
    <lable>manager name</lable>
    @Html.TextBoxFor(m => m.manager, new { @class = "form-control" })
    <div>
      
        <input type="submit" class="btn btn-success"  value="update" />
     </div>







</form>

Views/department/newdept.cshtml
@model Department
@{
    ViewData["Title"] = "newdept";
}

<form method="post" action="/department/savenewdept">
<div>
<lable>Deparment name</lable>
<input  asp-for="name" class="form form-control" value="@Model.name"/>
</div>

<div>
<lable asp-for="manager">Manager Name</lable>
<input  asp-for="manager" class="form form-control" />
</div>
<input  type="submit" value="save" class="btn btn-success" />

</form>