Controllers/acountController.cs
using MainProgram.Models;
using MainProgram.viewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MainProgram.Controllers
{
    public class acountController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signinmanager;

        public acountController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signinmanager)
        {
            this.userManager = userManager;
            this.signinmanager = signinmanager;
        }
        [HttpGet]
      
        public IActionResult register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> register(applicationUserVM newuser)
        {

            if (ModelState.IsValid)
            {
                ApplicationUser appuser = new ApplicationUser();
                appuser.UserName = newuser.username;
                appuser.PasswordHash = newuser.password;
                appuser.address = newuser.address;
                IdentityResult result = await userManager.CreateAsync(appuser, appuser.PasswordHash);
                //add cliams when create user this means that this claims will story in database for each user 
                //List<Claim> claims = new List<Claim>();
                //claims.Add(new Claim("adult", "yes"));    
                //claims.Add(new Claim("student", "yes"));
                //userManager.AddClaimsAsync(appuser, claims);

                if (result.Succeeded)
                {

                    userManager.AddToRoleAsync(appuser, "Student");
                    // List<Claim>clams=new List<Claim>();
                    //clams.Add(new Claim ( "color", "red" ));   use clam if i want to add external info additiion to id ,name,role
                    //signinmanager.SignInWithClaimsAsync(appuser,false, clams);

                    //create cookes
                    await signinmanager.SignInAsync(appuser, false);//create coockes for each client represented in id ,name,role
                                                                    // await  signinmanager.SignOutAsync();  //  this line to remove cookes from user
                    return RedirectToAction("Index", "instructor");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("password", item.Description);
                    }
                }

            }


            return View(newuser);
        }
        [HttpGet]
        public IActionResult AddAdmin()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> AddAdmin(applicationUserVM appuser)
        {
            if(ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser();

                user.UserName=appuser.username;
                user.PasswordHash = appuser.password;
                user.address=appuser.address;
              IdentityResult result=  await userManager.CreateAsync(user,user.PasswordHash);
                if(result.Succeeded)
                {
                   await userManager.AddToRoleAsync(user, "Admin");
                    //create cookes1
                   await signinmanager.SignInAsync(user, false);
                    return RedirectToAction("index","instructor");


                }
                else
                {
                    foreach(var item in result.Errors)
                    {
                        ModelState.AddModelError("",item.Description);
                    }
                }

            }



            return View(appuser);

        }
        public IActionResult logout()
        {
            //logout signinmanager
            signinmanager.SignOutAsync();
            return RedirectToAction("register");


        }

        public async Task< IActionResult> login(UserLoginVM userLlog)
        {
        
        
            if(ModelState.IsValid)
                {

                  ApplicationUser usermodel= await userManager.FindByNameAsync(userLlog.username);
                    if (usermodel != null) {
                
                     bool x=  await userManager.CheckPasswordAsync(usermodel, userLlog.password);
                        if (x)
                        {
                            await signinmanager.SignInAsync(usermodel,userLlog.rememberme);
                            return RedirectToAction("Index", "instructor");
                        }
                
                    }
                    ModelState.AddModelError("", "invalid userName or password");

                }


            return View(userLlog);        
        }
    }
}

Controllers/courseController.cs
using MainProgram.Models;
using MainProgram.Repository;
using Microsoft.AspNetCore.Mvc;

namespace MainProgram.Controllers
{
    public class courseController : Controller
    {
        private readonly IDepatmentRepository deptartment;
        private readonly IcourseRepository _courses;

        public courseController( IcourseRepository cor,IDepatmentRepository dept)
        {
            this.deptartment = dept;//new RepositoryDepartment();
            this._courses = cor;//new CourseRepository();
        }
        public IActionResult Index()
        {
            List<course> courseList =_courses.getAll();
            
            return View(courseList);

        }
       
        public IActionResult add()
        {

            List<Department> dept=deptartment.getALl();
            ViewData["dept"] = dept;

            return View();
        }

        public IActionResult SaveAdd(course c) {
            if (ModelState.IsValid)
            {


                //contex.Add(c);
                _courses.add(c);
                ////contex.SaveChanges();
                _courses.save();
               
                return RedirectToAction("Index");
            }
              List<Department> dept=deptartment.getALl();
            ViewData["dept"] = dept;
            return View("add",c);
        }
        public IActionResult checkdegree(int min_degree,int degree)
        {
            if(min_degree<degree)
            {

                return Json(true);
            }
            else
            {
                return Json("invlaide min-degree");
            }


        }
        public IActionResult checkHoure(int houres,int dept_id)
        {
            if (dept_id %2==0 && houres%2==0  )
            {

                return Json(true);

            }
            else
            {
                return Json("invlaide hourse /2");
            }
             if(dept_id%3==0&&houres%3==0) 
            {
                return Json(true);
            }
            else
            {

                return Json("invlaide hours number for this /3");
            }

        }
        public IActionResult edit(int  id)
        {
            course cour = _courses.GetByID(id);//contex.Courses.FirstOrDefault(c=>c.id==id);
            ViewBag.dept = deptartment.getALl();// contex.departments.ToList();
            return View(cour);

        }
        [HttpPost]
        public IActionResult saveedit(int id,course reslt)
        {
            ViewBag.dept = deptartment.getALl(); //contex.departments.ToList();

            course cour = _courses.GetByID(id);//contex.Courses.FirstOrDefault(c => c.id == id);
          
            
                cour.name = reslt.name;
                cour.degree = reslt.degree;
                cour.min_degree = reslt.min_degree;
                cour.dep_id = reslt.dep_id;
            ////contex.SaveChanges();
            _courses.save();
              //  RedirectToAction("index");

            
            return View("edit",reslt);


        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MainProgram</title>
    @* @* @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
      <link rel="stylesheet" href="~/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MainProgram.styles.css" asp-append-version="true" />
</head>
<body style="background-color:lightgrey">
    <header>
       @* @Html.Partial("_nav") *@
       <partial name="_nav" />
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="background-color:gainsboro ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MainProgram - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_nav.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@* @* @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                @if(User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="instructor" asp-action="index">instructors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="trainee" asp-action="Index">trainees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="course" asp-action="index">courses</a>
                    </li>
                    @if(User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="role" asp-action="newr">Add Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="addadmin">Add Admin</a>
                        </li>
                    }
                }else{
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">About US</a>
                    </li>

                }
              
            </ul>
            <ul class="navbar-nav flex-grow-2">
                
                
                @if(User.Identity.IsAuthenticated)
                {
                <li class="nav-item">
                   <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="logout">logout</a>
                </li>
                <li class="nav-item">
                   <a class="nav-link text-dark" asp-area="" >Welcome @User.Identity.Name</a>
                </li>
                }
                else{
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="register">Register</a>
                </li>
                }
            </ul>
        </div>
    </div>
</nav> *@ 

<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
        @* <a class="navbar-brand" href="#">Navbar</a> *@

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav flex-grow-1">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">

                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITI</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="instructor" asp-action="index">instructors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="trainee" asp-action="Index">trainees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="course" asp-action="index">courses</a>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="role" asp-action="newr">Add Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="addadmin">Add Admin</a>
                        </li>
                    }
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">About US</a>
                    </li>

                }

            </ul>
            <form class="d-flex">
                <ul class="navbar-nav flex-grow-2">


                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="logout">logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="">Welcome @User.Identity.Name</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="acount" asp-action="register">Register</a>
                        </li>
                    }
                </ul>
                <input class="form-control me-sm-2" type="search" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

Views/Shared/freeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Full Width Pics - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Header - set the background image for the header in the line below-->
    <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
        <div class="text-center my-5">
            <img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="..." />
            <h1 class="text-white fs-3 fw-bolder">Full Width Pics</h1>
            <p class="text-white-50 mb-0">Landing Page Template</p>
        </div>
    </header>
    <!-- Content section-->
    <section class="py-5">
        <div class="container my-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h2>Full Width Backgrounds</h2>
                    <p class="lead">A single, lightweight helper class allows you to add engaging, full width background images to sections of your page.</p>
                    <p class="mb-0">The universe is almost 14 billion years old, and, wow! Life had no problem starting here on Earth! I think it would be inexcusably egocentric of us to suggest that we're alone in the universe.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Image element - set the background image for the header in the line below-->
    <div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">
        <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
        <div style="height: 20rem"></div>
    </div>
    <!-- Content section-->
    <section class="py-5">
        <div class="container my-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    @RenderBody()
                    <h2>Engaging Background Images</h2>
                    <p class="lead">The background images used in this template are sourced from Unsplash and are open source and free to use.</p>
                    <p class="mb-0">I can't tell you how many people say they were turned off from science because of a science teacher that completely sucked out all the inspiration and enthusiasm they had for the course.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

Views/Shared/myLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div style="background-color:grey;height:100px">headder</div>
    <div class="clas1" style="display:flex">
        <div style="width:500px;background-color:red" >section</div>
        <div>
            @RenderBody()
        </div>

    </div>
    <div style="height:100px ;background-color:aqua">footer</div>
</body>
</html>