Models/instructor.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MainProgram.Models
{
	public class instructor
	{
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [DisplayName("imagee")]
        public string image { get; set; }
        [RegularExpression("(alex|cairo|assuit)",ErrorMessage ="please choise avalide address")]
        public string address { get; set; }
        public int salary { get; set; }
        [ForeignKey("course")]
        public int course_id {  get; set; }
        [ForeignKey("department")]
        public int department_id {  get; set; }
        public virtual course? course { get; set; }
        public virtual Department? department { get; set; }

	}
}

Controllers/instructorController.cs
using MainProgram.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MainProgram.Controllers
{
	public class instructorController : Controller
	{
		itientities context=new itientities();
		public IActionResult detals(int id)
		{

			instructor ins=context.instructors.FirstOrDefault(ins=>ins.id==id);
			return PartialView("_instructorspartial", ins);

		}
		public IActionResult show()
		{

          List<instructor>instlist = context.instructors.ToList();




			return View(instlist);
		}
		[Authorize]
		public IActionResult Index()
		{
		    List<instructor>resultmodel=context.instructors.OrderByDescending(s=>s.name).ToList();
			return View(resultmodel);
		}

		public IActionResult edit(int Id)
		{
			instructor instruct=context.instructors.FirstOrDefault(ins=>ins.id==Id);
			List<course>c=context.Courses.ToList();
			ViewBag.courses = c;

			return View(instruct);


		}


		public IActionResult saveedit(int Id,instructor inst) {
		

		     instructor intt= context.instructors.FirstOrDefault(i=>i.id==Id) ;
			intt.name=inst.name;
			intt.salary=inst.salary;
			intt.address=inst.address;
			intt.course_id=inst.course_id;
			intt.image=inst.image;
			context.SaveChanges();
            List<course> c = context.Courses.ToList();
            ViewBag.courses = c;
            return RedirectToAction("index");		
		
		}

		public IActionResult delete(int Id)
		{
			instructor intt=context.instructors.FirstOrDefault(inc=>inc.id==Id);
			context.Remove(intt);
			context.SaveChanges();
			return RedirectToAction("index");


		}
		public IActionResult add(instructor intt)
		{
			List<course> c=context.Courses.ToList();
			List<Department>dept=context.departments.ToList();
			ViewData["dept"] = dept;
			ViewData["courselist"] = c;
			return View(intt);

		}
		public IActionResult getallcourses(int Id)
		{
			List<course>cs=context.Courses.Where(c=>c.dep_id==Id).ToList();
			return Json(cs);
		}
		public IActionResult saveadd(instructor intt)
		{

			 if(intt.name==null)
			{
				List<course> c = context.Courses.ToList();
				ViewData["courselist"] = c;
                List<Department> dept = context.departments.ToList();
                ViewData["dept"] = dept;
                return RedirectToAction("add", intt);
			}
			context.instructors.Add(intt);
			context.SaveChanges();
			return RedirectToAction("index");



		}
		[HttpPost]
		public IActionResult search(string Name)
		{
			instructor instr = context.instructors.FirstOrDefault(c => c.name == Name);
			if(instr != null)
			{

				return View("search",instr);

			}

			return NotFound();


		}


		public IActionResult CreateCookies()
		{

			HttpContext.Response.Cookies.Append("name", "ahmed");
            HttpContext.Response.Cookies.Append("Age", "123");


			return Content("Cookies SAved");

		}
		public IActionResult ReadCookies()
		{
          string name = HttpContext.Request.Cookies["name"];
            string age = HttpContext.Request.Cookies["Age"];

			return Content($"the name ={name} and Age={age}");

		}
        public IActionResult CreateSession(string name)
        {

			HttpContext.Session.SetString("name", name);
            


            return Content("session  SAved");

        }
        public IActionResult ReadSession()
        {
            string name = HttpContext.Session.GetString("name");
            

            return Content($"the name ={name}");

        }
    }
}

Views/instructor/Index.cshtml
@{

	Layout = "_Layout";
}
@using MainProgram.Models;

@model List<instructor>
<div style="border:3px solid blue" id="insrtuctorDetals">

</div>
<h1 style="margin:auto">All Instructors</h1>
<table class="table table-bordered table-hover">
	<tr class="table-secondary">
			<th>id</th>
			<th>name</th>
			<th>address</th>
			<th>image</th>
		    <th>salary</th>
		   <th>Apdate</th>



	</tr>

	@foreach (instructor item in Model)
		{
			<tr>
						<td>@item.id</td>
			           <td><a href="#" onclick="get(@item.id)" > @item.name  </a></td>
						<td>@item.address</td>
						<td><img src="/images/@item.image" width=50px hight=50px /></td>
			             <td>@item.salary</td>
						<td><a href="/instructor/edit/@item.id">update</a></td>
						<td><a href="/instructor/delete/@item.id">delete</a></td>



			</tr>
			
		}


</table>

<form asp-action="search" asp-controller="instructor" method="post">
	<label>Serche By name</label>
	<input class="form form-control" type="text" name="name" value="" />
	<input type="submit" class="btn btn-primary"  value="Search" />
</form>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
	
	function get(id)
	{
		// console.log(id 
		event.preventDefault();
		
			$.ajax({
			url: "/department/detals/" + id, success: function (result) {
					// $("#div1").html(result);
					console.log(result)
					// document.getElementById("insrtuctorDetals").innerHTML = result;
				}
			});
	

	}



</script>

<button class="btn btn-success" style="margin-left:20%"> <a style="text-decoration:none ;color:white;font-size:20px" href="/instructor/add">Add new instructor</a></button>

Views/instructor/_instructorspartial.cshtml
  @model instructor

   
    
    <div class="card" style="width:400px ;margin-left:20px">
        <img class="card-img-top" src="/images/@Model.image" alt="Card image" style="width:100%">
        <div class="card-body">
            <p class="card-text">@Model.id</p>
            <h4 class="card-title">@Model.name</h4>
            <h4 class="card-title">@Model.salary</h4>
            <a href="#" class="btn btn-primary">See Profile</a>
        </div>
    </div>

Views/instructor/add.cshtml
@model instructor
@{
    ViewData["Title"] = "add";
    SelectList lis = new SelectList(ViewBag.courselist, "id", "name");
    SelectList list1 = new SelectList(ViewBag.dept, "id", "name");
}

<h1>add</h1>

<form action="/instructor/saveadd" method="post" style="width:50%;margin-left:30% ;background-color:darkgray" >
    
    <label asp-for="name"></label>
    <input class="form-control form-control-lg" asp-for="name" />

    <br />

    <label asp-for="image"></label>
    <input class="form-control form-control-lg" asp-for="image" />

    <br />
    <label asp-for="address"></label>
    <input class="form-control form-control-lg" asp-for="address" />
    <br />
    <label asp-for="salary"></label>
    <input class="form-control form-control-lg" asp-for="salary" />
    <br />
    <label asp-for="course_id"></label>
    <select id="c_id" class="form-control form-control-lg" asp-for="course_id" asp-items="lis">
    <option value="0">select course</option>    
    </select>
    <br />
    <label  asp-for="department_id"></label>
    <select id="d_id" class="form-control form-control-lg" asp-for="department_id" onchange="select()" asp-items="list1">
        <option value="0">select department</option>
    </select>
    <br />
    <input  type="submit"  />



</form>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    function select() {
                var departmentid = document.getElementById("d_id").value;
              var c_list = document.getElementById("c_id");
                console.log(departmentid);
        $.ajax({
            url: "/instructor/getallcourses/"+departmentid,
            success: function (result) {
               // $("#div1").html(result);
                //console.log(result);
                c_list.innerHTML = "";
                for(let item of result){
                  c_list.innerHTML += "<option value=" + item.id + ">" + item.name + "</option>";
                }
            }
        });

    }

</script>

Views/instructor/edit.cshtml
@model instructor
@{
    ViewData["Title"] = "edit";
    SelectList lis = new SelectList(ViewBag.courses, "id", "name");
}

<h1>Update</h1>

<form class="form-control" action="/instructor/saveedit/@Model.id"  method="post"  style="background-color:darkgray">
    
    <label asp-for="name"></label>
    <input class="form-control form-control-lg" asp-for="name" />
    <br />
    <label asp-for="address"></label>
    <input class="form-control form-control-lg" asp-for="address" />
    <br />
    <label asp-for="salary"></label>
    <input class="form-control form-control-lg" asp-for="salary" />
    <br />
    <label asp-for="image"></label>
    <input class="form-control form-control-lg" asp-for="image" />
    <br />
    <label asp-for="course_id"></label>
    <select asp-for="course_id" asp-items="lis">
        <option value="0"> select course</option>
    </select>
    @* <input class="form-control form-control-lg" asp-for="course_id" /> *@
    <br />
    <input type="submit" class="btn btn-success"/>



</form>

Views/instructor/search.cshtml
@model instructor
@{
    ViewData["Title"] = "search";
}

<h1>Data About Instructor</h1>


        <div>
            <label asp-for="image"></label>
            <img src="/images/@Model.image" style="width:100px;height:100px;-moz-border-radius:10px" />
        </div>
    <div>
        <label asp-for="name" ></label>
        <input class="form form-control" type="text" name="name"  value="@Model.name" />
    </div>

    <div>
        <label asp-for="address"></label>
        <input class="form-check form-control" type="text" name="name" value="@Model.address" />
    </div>
    <div>
        <label asp-for="address"></label>
        <input class="form-check form-control" type="text" name="name" value="@Model.address" />
    </div>
    <div>
        <label asp-for="salary"></label>
    <input class="form form-control" type="text" name="name" value="@Model.salary" />
    </div>
   

Views/instructor/show.cshtml
@using MainProgram.Models

@model List<instructor>




<h1 style="margin:auto">Show all instrutors</h1>

    @* <div style="background-color:aquamarine ;display:flex; float:right grid-template-columns: repeat(3, 1fr);gap: 10px;"> *@

   
    
        <div  style="display:flex;flex-direction:row"> 

   

    @foreach(var item in @Model )
    {
      

               <partial name="_instructorspartial" model="item"></partial>
         

    }
        
  

@* </div> *@




        </div>